<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%> <!-- //page is being generated by 8-bit unicode java, diocritical accepting -->
<%@ taglib prefix "c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Testing Citation</title>
</head>
<body>
<h1>Hello world!</h1>
<form>
	<c:if test="${empty param.citation}">
		Citation: <input type = "text" name="citation" value="${param.citation}">
	</c:if>
	<c:if test="${not empty param.citation}"> <!-- will evaluate to true or false -->
		<br><br>
		<c:out value="${param.citation }"/> <!-- param is a javascript variable automatically, every element of a form is available in param.something -->
		<c:set var="split" value="${fn:split(param.citation,'. ')}"/> <!-- split will be an array, fn:split will be an array -->
		<br><br>
		<c:out> value="${split}"/> <!-- will spit out the address on array in memory -->
		<br><br>
		<c:foreach var="i" value="0" end="5"> <!--  is called an iterater, i is the index -->
			<c:out value="${split[i]}"/>
		</c:foreach>
		<br><br>
		<ul>
			<c:forTokens items="${param.citation}" delims=".:" var="bibPiece"> <!-- splits for you, expects to be looking for tokens within string input, each character of delims is treated as separate delims, will split on . and :, cannot split on instances of .: where delimiter is . with : after it -->
				<li>
					<c:out value="bibPiece"/>
				</li>
			</c:forTokens>
		</ul>
		<br><br>
		<ul>
			<c:forTokens items="{split[1]}" delims="," var="author">
				<c:out value="${author} ${split[fn:length(split)-1]} }"/> <!-- can have multiple ${} within a "" when passing in values, will convert them all to strings, negative indexing of arrays is not supported -->
			</c:forTokens>
		</ul>
	</c:if>
	</form>
</body>
</html>